### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by jjtParadox** [Valiec/DeeperCaves#26]
I've noticed this mod has some code in the `net.minecraft` package ([`MaterialMoltenIron`] (https://github.com/Valiec/DeeperCaves/blob/master/src/main/java/net/minecraft/block/material/MaterialMoltenIron.java) and [`RenderDeepSpider`] (https://github.com/Valiec/DeeperCaves/blob/master/src/main/java/net/minecraft/client/renderer/entity/RenderDeepSpider.java)). Minecraft mods should never have code in the `net.minecraft` package unless they know exactly what they are doing. The two files mentioned above can easily be moved into `com.kpabr.DeeperCaves` without issue (Right-click > Refactor/Rename in most IDEs).

Also, there is a large opportunity for cleaning up the mod by putting classes in proper packages (`BiomeGen` classes in `com.kpabr.DeeperCaves.world.gen`, `Block` classes in `com.kpabr.DeeperCaves.block`, `ChunkProvider` classes in `com.kpabr.DeeperCaves.world.chunk`, etc.).

Package organization is all personal preference, but it helps greatly in making code more manageable and readable.

**Comment by Valiec** [comment]
I've moved the two net.minecraft* src files. I am leaving the issue open since I am still going to clean up the package hierarchy a bit more.
