### ISSUE TITLE
Ore Dictionary

### ISSUE THREAD

**Issue by Zsashas** [Valiec/DeeperCaves#29]
Aquamarine Block is registered blockSapphire.

Aquamarine Block is also registered as oreAquamarine, not blockAquamarine.

Ametrine Block is registered as blockAquamarine instead of blockAmetrine.

Aquamarine Ore is not registered as anything.

Abandoned Caves Stone is registered as both cobble and stone (intended?)

"Dark" and "Abandoned Caves" ores are not registered as anything (Compressed and Deep Compressed are fine).

![image](https://cloud.githubusercontent.com/assets/6917535/12074019/cf694c64-b0f1-11e5-8dde-358960b68e23.png)

![image](https://cloud.githubusercontent.com/assets/6917535/12074024/850bfbca-b0f2-11e5-974c-5ae05476eff2.png)

![image](https://cloud.githubusercontent.com/assets/6917535/12074028/a58aceda-b0f2-11e5-8a25-d81d2ac1d925.png)

**Comment by Valiec** [comment]
Thanks for finding this!

These are all bugs except Abandoned Caves Stone being registered as stone and cobblestone, which is intentional (actually, dark stone should be too)

**Comment by Valiec** [comment]
This should be fixed in the latest commit. Closing.
