### ISSUE TITLE
Mod Download

### ISSUE THREAD

**Issue by Chomper32** [Valiec/DeeperCaves#35]
I love the mod and I want to try it out (as a player) but I cant find the download... Sorry about putting it in the issues folder... i am probably just blind.

**Comment by Valiec** [comment]
To download the mod, go to the Minecraft Forum thread at http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2350259-deeper-caves-go-beyond-the-void-beta-7000 (the second link in the readme) and click the "Download Deeper Caves 0.5.0 For Minecraft 1.7.10" link.

**Comment by Valiec** [comment]
This was resolved, but I forgot to close it.
