### ISSUE TITLE
Some liquids are destroyed upon collection (affects other mod fluids)

### ISSUE THREAD

**Issue by Shahelion** [Valiec/DeeperCaves#46]
Attempting to use an empty bucket on certain liquids simply destroys them. Narrowed it down to this mod causing it. Using current latest release.

Fluids that cannot be picked up with a bucket from in the world:
Life Essence (Blood Magic)
Oil and Fuel (Builcraft)
All Chromaticraft fluids
Tinkers Construct molten metals and Slime
Liquid Death and Purifying Fluid (Thaumcraft)
Liquid Coralium and Liquid Antimatter (Abyssalcraft)

Things that CAN be picked up:
Water
Lava
Mushroom and Vishroom Soup (Automagy)
Venenium (DeeperCaves)
ExtraTiC molten metals
Honey and Formic Acid (Erebus)
Spectral Dew (Netherlicious)
Spirit and Hollow Tears (Witchery)

**Comment by Valiec** [comment]
I probably broke the bucket handler trying to handle fragmented bedrock buckets and Venenium, I'll see about fixing it.

**Comment by Shahelion** [comment]
How important are the bedrock buckets? Would it be easier to switch the fluids to just use the regular bucket system?

**Comment by Shahelion** [comment]
Fixed with newest release!
